spring:
  application:
    name: agrosat

  datasource:
    url: # Aqui vai a url do banco
    username: # Aqui vai o usuário (RM...)
    password: # Aqui vai a senha (data de aniversário)

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

jwt:
  secret: # Aqui vai o token secret do JWT tem q gerar
  expiration: 3600000 # 1 hora

mqtt:
  broker:
    url: tcp://localhost:1883
  client:
    id: agrosat-backend
  topic:
    filter: agrosat/+/+/+
  qos: 1

# Springdoc OpenAPI (Swagger UI)
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
  api-docs:
    path: /v3/api-docs
  show-actuator: false
