spring:
  application:
    name: agrosat

  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl # Aqui vai a url do banco
    username: Rm555448 # Aqui vai o usuário (RM...)
    password: 290106 # Aqui vai a senha (data de aniversário)

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

jwt:
  secret: eff6d494bd125addc10eee441a8e54140e5f4e856f9ad42e91bfd7370e4f245b # Aqui vai o token secret do JWT tem q gerar
  expiration: 3600000 # 1 hora